---
title: "Mc inSileco"
author: "McCann + inSileco"
from: markdown+emoji
format: 
  revealjs:
    theme: [default, custom.scss]
    slide-number: true
    transition: fade
    css: styles.css
    incremental: false
    toc: false
    toc-depth: 2
    include-in-header:
      - text: |
          <!-- Font Awesome 6 -->
          <link rel="stylesheet"
                href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
---


## Agenda 

- inSileco Offer (5min)
- inSileco Systems (1min)
- inSileco Academy (30min)
- inSileco Intelligence (30min)
- Discussions/Next steps


# inSileco Offer

## Mission statement

> We operationalize environmental management by building the capacity, tools, and systems that environmental professionals and organizations need to work confidently and efficiently.


## Entities 

### Description

- **inSileco Blog** — Open insights on environmental management and new technologies
- **inSileco Academy** — Capacity building for environmental professionals
- **inSileco Systems** — Build and transfer operational data and modeling systems.
- **inSileco Intelligence** — Deliver decision-ready environmental risk assessments.

## Entities

### Purpose

- **inSileco Blog** - Leads Generator
- **inSileco Academy** — Leads Generator + income flow
- **inSileco Systems** — Income flow
- **inSileco Intelligence** — Revenue generator


## Offer

#### DIY: Do it Yourself 

- inSileco Blog: free content 
- inSileco Academy: Autonomous courses

#### DWY: Do it With You 

- inSileco Academy: Workshops + Coaching

#### DFY: Do it For You 

- inSileco Systems: Contracts
- inSileco Intelligence: Subscriptions

# Offers example 

## inSileco Academy 

- Intro workshop/coaching (DWY)
  - Become vastly more efficient by  Integrating AI and reproductibility in your professional life as an environmental professional 
  - 10-20 person monthly cohort
  - half day workshop
  - 4x 1h follow-up targeted events
  - 5h support post-workshop (usable within 3 months)

## inSileco Academy

- Specialized workshop (DWY)
  - Bring your own project to develop R packages, Shiny applications, integrated datasets, etc. 
  - 2 days workshop
  - bring your own project 
  - intro workshop completed |(50% discount on it)
  - 10h post-workshop support (usable within 6 months)

## inSileco Systems

- From academy to systems (DWY -> DFY)
  - We complete the project your began in your specialized workshop
  - <20k$ -> 25% credit on workshop
  - 20k$ - 50k$ -> 50% credit on workshop
  - over 50k$ -> 100% credit on workshop



# inSileco Systems

## We build system for you

- Custom data solutions
  - consulting
  - R packages 
  - Shiny Apps




# inSileco Academy

## Autonomous courses 

- Example: Ecological modules for student
- Example: Reproducible research

## Coaching 

- Example: Grant Applications for PIs
- Example: Create your first R package


## Projects 

### System thinking 

- Todo: draft app 

### Summer School

- This year?



# inSileco Intelligence 

# Ecosystem-based Management / Environmental intelligence

## CEA in the Gret Lakes 

## Protray of biodiversity 

## inSileco Plateform



# Next Steps
